pipeline {
    agent {
        label 'windows'
    }
    stages {
        stage('Terraform Plan') {
            steps {
                bat 'terraform init'
                bat 'terraform plan -no-color'
            }
        }
        stage('Approval') {
            steps {
                script {
                    def userInput = input(id: 'confirm', message: 'Apply Terraform?', parameters: [ [$class: 'BooleanParameterDefinition', defaultValue: false, description: 'Apply terraform', name: 'confirm'] ])
                }
            }
        }
    }
}
